// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Security.Database;

namespace Security.Migrations
{
    [DbContext(typeof(BreakingApplicationContext))]
    partial class BreakingApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Security.Models.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Email")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("NotSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = new byte[] { 228, 231, 75, 1, 106, 129, 78, 75, 140, 215, 49, 22, 187, 16, 218, 105 },
                            Login = "Tom",
                            NotSalt = new byte[] { 40, 199, 122, 210, 85, 208, 76, 79, 152, 139, 19, 118, 39, 197, 39, 148 },
                            Password = new byte[] { 180, 180, 112, 155, 204, 206, 94, 71, 164, 20, 155, 27, 224, 148, 101, 96 }
                        },
                        new
                        {
                            Id = 2,
                            Email = new byte[] { 184, 61, 165, 131, 204, 206, 146, 78, 176, 139, 233, 223, 246, 229, 49, 109 },
                            Login = "Alice",
                            NotSalt = new byte[] { 33, 137, 240, 110, 52, 125, 2, 77, 180, 251, 250, 219, 207, 208, 221, 58 },
                            Password = new byte[] { 3, 21, 124, 48, 31, 122, 224, 73, 149, 29, 118, 193, 80, 167, 150, 154 }
                        },
                        new
                        {
                            Id = 3,
                            Email = new byte[] { 18, 131, 213, 245, 250, 96, 219, 71, 128, 75, 119, 46, 94, 223, 70, 247 },
                            Login = "Sam",
                            NotSalt = new byte[] { 121, 80, 249, 138, 229, 241, 173, 79, 164, 28, 235, 20, 101, 64, 130, 126 },
                            Password = new byte[] { 236, 238, 126, 69, 164, 169, 160, 65, 129, 23, 43, 52, 141, 186, 169, 215 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
