// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Security.Database;

namespace Security.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Security.Models.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Email")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("NotSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = new byte[] { 60, 135, 198, 192, 34, 224, 52, 74, 151, 251, 101, 36, 45, 197, 92, 214 },
                            Login = "Tom\r\n",
                            NotSalt = new byte[] { 21, 136, 209, 60, 146, 133, 163, 70, 178, 71, 202, 172, 63, 117, 91, 5 },
                            Password = new byte[] { 231, 93, 210, 246, 240, 163, 76, 71, 131, 95, 93, 74, 129, 127, 236, 220 }
                        },
                        new
                        {
                            Id = 2,
                            Email = new byte[] { 107, 38, 250, 205, 164, 105, 15, 79, 168, 84, 163, 228, 33, 247, 66, 58 },
                            Login = "Alice\r\n",
                            NotSalt = new byte[] { 187, 155, 245, 196, 131, 166, 111, 74, 185, 145, 56, 94, 142, 94, 64, 150 },
                            Password = new byte[] { 85, 144, 49, 6, 138, 61, 150, 69, 140, 154, 0, 135, 84, 57, 135, 131 }
                        },
                        new
                        {
                            Id = 3,
                            Email = new byte[] { 153, 213, 143, 171, 198, 227, 25, 71, 140, 130, 95, 66, 236, 34, 171, 146 },
                            Login = "Sam\r\n",
                            NotSalt = new byte[] { 169, 39, 111, 211, 118, 175, 79, 70, 191, 188, 14, 129, 72, 148, 187, 26 },
                            Password = new byte[] { 85, 244, 252, 71, 220, 38, 59, 65, 183, 93, 139, 237, 148, 214, 87, 175 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
